### ISSUE TITLE
Revision of TV following submission feedback

### ISSUE THREAD

**Issue by thibautjombart** [Bisaloo/Epidemiology#3]
I am planning on making a revision of the TV via PR to address the points raised after initial submission [here](https://github.com/cran-task-views/ctv/issues/25#issuecomment-1126606465).

I will list things to do here; assume I am doing them unless otherwise stated:

- [x] @Bisaloo rename the task view to just *epidemiology* (this project page, I will update links as needed)
- [x] @[mjrolland](https://github.com/mjrolland) drafts a section for 'Environmental epidemiology' here in an issue
- [x] incorporate this section into a revised TV
- [x] add [nhanesA](https://cran.r-project.org/package=nhanesA) to the TV
- [x] add links to existing task views using `view(...)`
- [x] remove mentions of graphics and multivariate TV as they are getting archived
- [x] add people from this [discussion](https://github.com/cran-task-views/ctv/issues/25#issuecomment-1126606465) as contributors
- [x] clarify the scope, mention that genetic epi / GWAS is out of scope, emphasize that this is WIP and contributions are welcome
- [ ] update TV for new packages (or deprec ones)

Thoughts?

**Comment by Bisaloo** [comment]
>  @Bisaloo rename the task view to just epidemiology (this project page, I will update links as needed)

Done :+1:
